project_name: gh-rdm

builds:
  - binary: gh-rdm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto

changelog:
  sort: asc
