project_name: gh-rdm

builds:
  - binary: gh-rdm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

changelog:
  sort: asc
